const IActionTypes = {
    SET_PAWN_ELEMENT_POSITION : 'SET_PAWN_ELEMENT_POSITION',
    START_GAME: 'START_GAME',
    UPDATE_PAWN_POSITIONS: 'UPDATE_PAWN_POSITIONS',
    GAME_COMPLETED: 'GAME_COMPLETED'
} 

export default IActionTypes;